---
title: "Homework 4.1"
author: "Drew Remmenga"
date: "2024-07-19"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\newpage
Exercise 5.4 (a)
```{r}
pnorm(355,355.2,.5)
```
\newpage
Exercise 5.4 (b)
```{r}
z=(355-355.2)/(.5/sqrt(6))
pnorm(z,0,1)
```
\newpage
Exercise 5.5 (a)
Normal
\newpage
Exercise 5.5 (b)
V has a lower variance so it will be lower.
\newpage
Exercise 5.5 (c)
```{r}
z1=(35-40)/(15/sqrt(50))
z2 =(45-40)/(15/sqrt(50))
pnorm(z2,0,1)-pnorm(z1,0,1)
z1=(35-40)/(15/sqrt(100))
z2=(45-40)/(15/sqrt(100))
pnorm(z2,0,1)-pnorm(z1,0,1)
```
\newpage
Exercise 5.6
Yes due to the central limit theroem. This will still be approximately corrected becaue the mean is assymptotically normal. 
```{r}
z=((4000/50)-78)/(12/sqrt(50))
pnorm(z,0,1)
```
\newpage
Exercise 5.14 (a)
```{r}
mu=100*.2
mu
v= 100*.2*(1-.2)
sqrt(v)
```
\newpage
Exercise 5.14 (b)
```{r}
p=.2
p
v=.2-.2^(2)
sqrt(v)
1-pbinom(30,100,.2)
z=(30-20)/4
1-pnorm(z,0,1)
answers=rbinom(1,100,.2)
prop.test(answers,30)
```
\newpage
Exercise 5.14 (c)
